### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by riccardobl** [mohamnag/javafx_webview_debugger#1]
Hi, under which license is this code released?

**Comment by mohamnag** [comment]
I'm sorry that I cant answer this question. I have just republished (and done minor changes) this code on GitHub for easier usage. The original author of code is not responding to my (and other's) licence information requests. You can follow, try to reach him here: http://stackoverflow.com/a/34444807/438727

**Comment by boskokg** [comment]
This code has open source license dependency. Code that I wrote can be used freely. I am glad that I could help someone with this, since I spent days trying to include debugger. Enjoy ;-)

**Comment by mohamnag** [comment]
@boskokg this is great news, I will then add an MIT license, all the credit goes to you ;)
