### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by dikium** [mohamnag/javafx_webview_debugger#2]
How to install your library? Thanks.

**Comment by mohamnag** [comment]
please try following jitpack dependency, let me know if this works and I will also put it on the readme file:

```
dependencies {
	        compile 'com.github.mohamnag:javafx_webview_debugger:-SNAPSHOT'
	}
```

**Comment by mohamnag** [comment]
for that to work, you have to add jitpack source too:

```
repositories {
			...
			maven { url 'https://jitpack.io' }
		}
```

**Comment by dikium** [comment]
Yes, this is works! Thank you!

**Comment by mohamnag** [comment]
thanks for feedback, I also updated the readme.

**Comment by Bizarrus** [comment]
Can you provide compiled binarys without jitpack or other depends package managers?
We can't use jitpack on our company for licensing/copyright problems. It's not cool, if the packages will be only available on jitpack.

**Comment by mohamnag** [comment]
@Bizarrus setting up the publication to maven central is a lengthy and time consuming job. I'm not sure if I can find the time but will try to do it during next few days. Anyway, its a good practice not to comment on a closed ticket (even a less relevant one) for new requests.

**Comment by mohamnag** [comment]
@Bizarrus so it is now setup and published to maven central here: https://search.maven.org/artifact/com.mohamnag/javafx-webview-debugger/0.0.1/jar
