### ISSUE TITLE
Console not working

### ISSUE THREAD

**Issue by Valrog** [mohamnag/javafx_webview_debugger#3]
Hello, I am trying to debug JavaFX WebView with this tool, but I cannot get Chrome console to write out anything. It almost seems as if `console.log` is simply ignored whenever it appears in my scripts.

This is my WebView version when I call `view.getEngine().getUserAgent()` : Mozilla/5.0 (Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) JavaFX/8.0 Safari/602.1

**Comment by ShqipognjaLL** [comment]
The only console log I get is "navigated to" and the filepath of the initial index.html
I have disabled firebug as well so there should be no interference there.

**Comment by mohamnag** [comment]
As I have not used this recently, I can only share what is left in my mind about console logs. The console log does not work out of the box, the best solution is to override it in JavaScript to pass the logs to a Java function and output/use them in your Java code.

This overriding is a thing provided by JavaFX and is not specific to this project.

**Comment by Valrog** [comment]
Alright, I've implemented a bridge class that passes logging to Java now. I guess you can close this now if there isn't a way to make the console run in Chrome.

If anyone else comes looking, this is what I've done. I'll make this into a proper Gist once I get more time.

Bridge class

```java
public class JavaBridge {

    public void log(String text) {
        System.out.println(text);
    }
}
```
Main class

```java
final URL urlTrainMaps = getClass().getResource("/html/trainmaps.html");
        webEngine.setJavaScriptEnabled(true);

        webEngine.getLoadWorker().stateProperty().addListener(
                new ChangeListener<State>() {
            @Override
            public void changed(ObservableValue ov, State oldState, State newState) {

                if (newState == Worker.State.SUCCEEDED) {
                    JSObject window = (JSObject) webEngine.executeScript("window");
                    JavaBridge javaBridge = new JavaBridge();
                    window.setMember("logger", javaBridge);
                }
            }
        });

        webEngine.load(urlTrainMaps.toExternalForm());
```

JavaScript example

```javascript
function drawTrainRoute(routeLineString) {

    var rdvFeature = wktFormat.readFeature(routeLineString, {
        dataProjection: 'EPSG:4326',
        featureProjection: 'EPSG:3857'
    });

    trainRouteSource.addFeature(rdvFeature);

    logger.log("Train route drawn!"); // This will be visible in the Java console

    // Fits route to extent
    fitExtent();
}
```

**Comment by mohamnag** [comment]
thanks for posting the code, it would be great if you can fork the readme and add this into it. as much as I can remember this is also the solution I found at that time and direct support of console was not possible.

**Comment by mohamnag** [comment]
PS: I think you can just overwrite console object not to change your JS code like this:

```
window.setMember("console", javaBridge);
```

**Comment by Valrog** [comment]
I have just tried this and can confirm that overriding the console is possible. I still like to call it under a different name so I do not forget that a workaround is necessary otherwise.

**Comment by Valrog** [comment]
Actually, I've found that it is preferable to override the console. It is possible that hidden calls are made (Maybe it's a JavaScript thing, maybe it's an OpenLayers thing I don't know) to the console, and since WebView's console is undefined, scripts will stop working after that point. I've managed to fix some WebView problems by overriding it. I'll update the Readme once I get home.

**Comment by mohamnag** [comment]
I can imagine one will use some libraries and almost every JS lib that you find in the wild will have some console calls, so as you say this will probably won't be a bad idea to override that.

**Comment by Valrog** [comment]
It seems that this has now been resolved in some way.
