### ISSUE TITLE
Another JavaFX WebView debugger implementation

### ISSUE THREAD

**Issue by vsch** [mohamnag/javafx_webview_debugger#7]
@mohamnag, I thought you might like a full featured implementation of Chrome Dev Tools web-socket server that was inspired by your code, for which I am grateful. I spent two years working with logs for JavaScript debugging in WebView and had enough of that. 

I needed a debugger and started with your code but could not get the jetty library to work in an IntelliJ plugin. Rewrote the implementation for https://github.com/TooTallNate/Java-WebSocket.

I was not satisfied with lack of real console or other Chrome Dev Tools features. I implemented fully functioning console and commandLineAPI using some JavaScript, Java and a proxy to compensate for WebViews missing implementation.

It does require a bit more code to get into WebView but not much considering you get full featured Chrome Dev Tools debugging. Including one click navigation to source from the console log.

Take a look at the [Web View Debug Sample] application for a working example. You can play with it and debug the embedded scripts before deciding whether you want to instrument your own application for Chrome Dev Tools debugging.

![main-screen](https://raw.githubusercontent.com/vsch/WebViewDebugSample/master/assets/images/main-screen.png)

[Web View Debug Sample]: https://github.com/vsch/WebViewDebugSample

**Comment by mohamnag** [comment]
ok, thanks for heads up. There you have done a great job, I have moved on to rather using web apps packed in electron than JavaFX but I think for a lot of people this debugging issue is going to be rather relevant so I will add a link to your library (https://github.com/vsch/Javafx-WebView-Debugger) on the read me for people who happen to land here.

**Comment by vsch** [comment]
Thank you for the promo. I also think that a lot of people can benefit from having real debugging for JavaFX WebView. I know I would have preferred to find a solution rather have to take the time to create it myself.

**Comment by mohamnag** [comment]
I personally appreciate your efforts, thats these small steps that moves us as a community forward.
